test-utility
dummySuggestionGoEuro

^ SuggestionGoEuro newForDictionary: (Dictionary newFrom: {'_id'->371577. 'alternativeNames'->Dictionary new. 
                                                           'coreCountry'->false. 
                                                           'country'->'Brazil'. 
                                                           'countryCode'->'BR'. 
                                                           'countryId'->31. 
                                                           'distance'->nil. 
                                                           'fullName'->'Rio de Janeiro, Brazil'. 
                                                           'geo_position'->(Dictionary newFrom: {'latitude'->(-22.90278). 
                                                                                                 'longitude'->(-43.2075)}). 
                                                           'iata_airport_code'->nil. 
                                                           'inEurope'->false. 
                                                           'key'->nil. 
                                                           'locationId'->3737. 
                                                           'name'->'Rio de Janeiro'. 
                                                           'names'->(Dictionary newFrom: {'ca'->'Rio de Janeiro'. 
                                                                                          'es'->'Río de Janeiro'. 
                                                                                          'ru'->'Рио-де-Жанейро'. 
                                                                                          'zh'->'里约热内卢' }). 
                                                           'type'->'location' }).